services:
  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
      - ["setFramework", ["@contao.framework"]]
    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
      - ["setContainer", ["@service_container"]]

  huh.api.event_listener.data_container.api_app_action_listener:
    class: HeimrichHannot\ApiBundle\EventListener\DataContainer\ApiAppActionListener
    public: true
    autowire: true