services:
  huh.api.backend.api_app:
    public: true
    class: HeimrichHannot\ApiBundle\Backend\ApiApp
    arguments:
    - "@contao.framework"
  huh.api.routing.matcher:
    class: Symfony\Component\HttpFoundation\RequestMatcher
    calls:
    - ["matchAttribute", ["_scope", "api"]]
  huh.api.routing.login.matcher:
    class: Symfony\Component\HttpFoundation\RequestMatcher
    calls:
    - ["matchAttribute", ["_scope", "api_login"]]
  huh.api.jwt_coder:
    class: HeimrichHannot\ApiBundle\Security\JWTCoder
    arguments:
    - "%secret%"
  huh.api.security.authenticator:
    class:  HeimrichHannot\ApiBundle\Security\ApiAuthenticator
    arguments:
    - "@contao.framework"
    - "@huh.api.jwt_coder"
    - "@translator"
  huh.api.security.user_provider:
    class: HeimrichHannot\ApiBundle\Security\User\ApiUserProvider
    arguments:
    - "@contao.framework"
    - "@translator"
  huh.api.security.member_authenticator:
    class: HeimrichHannot\ApiBundle\Security\MemberAuthenticator
    arguments:
    - "@contao.framework"
    - "@huh.api.jwt_coder"
    - "@translator"